BootStrap:docker
From:centos:latest
MirrorURL: http://mirror.centos.org/centos-%{OSVERSION}/%{OSVERSION}/os/$basearch/
Include: yum

%runscript
echo "This gets run when you run the image!" cd /code exec echo "Hello" "$@"

%post
   echo "Hello from inside the container"
   mkdir /usr/local/mvapich
   yum -y install vim-minimal wget libibverbs-devel librdmacm-devel libibumad-devel libibmad-devel libmlx5 libmlx4
   yum -y groupinstall "Development Tools"
   wget http://mvapich.cse.ohio-state.edu/download/mvapich/mv2/mvapich2-2.1.tar.gz
   tar xvf mvapich2-2.1.tar.gz
   cd mvapich2-2.1
   ./configure --prefix=/usr/local/mvapich
   make -j4
   make install
/usr/local/mvapich/bin/mpicc examples/hellow.c -o /usr/bin/hellow
